export const HOME = '/home'
export const JOURNALDETAILS = '/home/journalentry/:entryId'
export const JOURNALFORM = '/home/journalform'
export const FAVLIST = '/home/favejournalentries'
export const LOGIN = '/login'
export const REGISTER = '/register'
